openai_api_key = "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"
databricks_host = "https://dbc-be6ccbbf-507f.cloud.databricks.com"
databricks_token = "dapi3b189367a0a8675c591b2229076c226b"
http_path = "/sql/1.0/warehouses/a72316754cc9905a"
